---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: grafana
  namespace: default
spec:
  serviceAccountName: default-ns-sa
  packageRef:
    refName: collosus.gov
    versionSelection:
      constraints: 1.0.0
  
