apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: prometheus
  namespace: apps-mgmt
spec:
  serviceAccountName: kapp-cluster-admin
  packageRef:
    refName: prometheus.community.tanzu.vmware.com
    versionSelection:
      constraints: 2.27.0
  values:
  - secretRef:
      name: pkg-demo-values
---
apiVersion: v1
kind: Secret
metadata:
  name: pkg-demo-values
  namespace: apps-mgmt
stringData:
  values.yml: |
    ---
    namespace: prometheus-addon
