---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: collosus-package
  namespace: default
spec:
  fetch:
    imgpkgBundle:
      image: index.docker.io/vnarayanan/collosus-repo:1.0.0
