apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: simple-app.corp.com.1.0.0
spec:
  refName: simple-app.corp.com
  version: 1.0.0
  releaseNotes: |
    Initial release of the simple app package
  valuesSchema:
    openAPIv3:
      svc_port: 80
      app_port: 80
      hello_msg: stranger
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: index.docker.io/vnarayanan/simple-package@sha256:8b199051061fcfef126446e82ddcf024c3c014b150a7fd916b62fe246eb3798b
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
      deploy:
      - kapp: {}
