---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: simple-package-repo
  namespace: default
spec:
  fetch:
    imgpkgBundle:
      image: index.docker.io/vnarayanan/pkg-repo@sha256:96a0d26c28e3759e986961cf3d433e0ea4c7ef0ec2e74b974102b36836ff8743
