apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: collosus.nasic.gov
spec:
  refName: collosus.nasic.gov
  version: 1.0.0
  releaseNotes: |
    Initial release of the grafana app package
  valuesSchema:
    openAPIv3: null
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: index.docker.io/vnarayanan/grafana@sha256:89c0a76561388c9fe93ad069cc967bcf306b66bbcac27177dbf8e188efa32d9f
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
      deploy:
      - kapp: {}
